# NetBouncer 配置文件示例

# 监控配置
monitor:
  interface: "eth0"  # 网络接口名称（留空自动选择）
  exclude_subnets: "127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # 排除的子网（逗号分隔）
  window: 60  # 监控时间窗口（秒）
  timeout: 86400  # 连接超时时间（秒，24小时）

# 防火墙配置
firewall:
  chain: "NETBOUNCER"  # iptables链名称
  ipset: "netbouncer"  # ipset名称
  type: "ipset"        # 防火墙类型：iptables, ipset, mock

# Web服务配置
web:
  listen: "0.0.0.0:8080"  # Web服务监听地址

# 数据库配置
database:
  driver: "sqlite"        # "sqlite", "mysql", "postgres"
  host: ""                # 数据库主机地址（sqlite不需要）
  port: 0                 # 数据库端口号（sqlite不需要）
  username: ""            # 数据库用户名（sqlite不需要）
  password: ""            # 数据库密码（sqlite不需要）
  database: "netbouncer.db"  # 数据库名称或文件路径
  dsn: ""                 # 数据库连接字符串（可选，优先级高于其他配置）
  log_level: "info"       # SQL日志级别: "silent", "error", "warn", "info"

# 初始规则配置
rules:
  # 示例：创建一个默认的封禁组
  - group: "blocked"
    groupDescription: "默认封禁组"
    action: "block"
    override: false
    ipNets:
      - "192.168.1.100"
      - "10.0.0.0/24"
  
  # 示例：创建一个白名单组
  - group: "whitelist"
    groupDescription: "白名单组"
    action: "allow"
    override: true
    ipNets:
      - "127.0.0.1"
      - "192.168.1.1"

# 防火墙类型配置示例：

# ipset模式（默认，高性能）
# firewall:
#   type: "ipset"
#   ipset: "netbouncer"

# iptables模式（兼容性好）
# firewall:
#   type: "iptables"
#   chain: "NETBOUNCER"

# mock模式（调试用）
# firewall:
#   type: "mock"

# 数据库配置示例：

# SQLite数据库（默认，适合单机部署）
# database:
#   driver: "sqlite"
#   database: "netbouncer.db"  # SQLite数据库文件路径
#   # 其他字段对于SQLite可以留空

# MySQL数据库（适合生产环境）
# database:
#   driver: "mysql"
#   host: "localhost"
#   port: 3306
#   username: "netbouncer"
#   password: "password"
#   database: "netbouncer"

# PostgreSQL数据库（适合复杂查询）
# database:
#   driver: "postgres"
#   host: "localhost"
#   port: 5432
#   username: "netbouncer"
#   password: "password"
#   database: "netbouncer"

# 使用DSN连接字符串（优先级最高）
# database:
#   dsn: "mysql://user:password@localhost:3306/netbouncer" 